name: Ruby
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install RVM
      run: gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
    - run: \curl -sSL https://get.rvm.io | bash -s stable
    - run: source $HOME/.rvm/scripts/rvm
    - run: rvm install 2.7
    - run: gem install bundler
    - run: bundle install
    - run: bundle exec ruby test.rb
