name: Ruby
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.0
    - name: Install dependencies
      run: |
        rvm gemset create puppet-check
        gem install bundle
    - name: validation
      run: |
        bundle
        bundle exec rake validate
        if [ $? -eq 0 ]; then
            echo "Validate checks passed!"
        else
            echo "Validate checks failed!"
            rvm gemset delete puppet-check --force
            exit 1
        fi
	bundle exec rake strings:generate

