name: Ruby Rake Tests
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.1
    - name: Install dependencies
      run: |
        bundle install
    - name: Run Rake tests
      run: |
        bundle exec rake validate
        if [ $? -eq 0 ]; then
          echo "Validate checks passed!"
        else
          echo "Validate checks failed!"
          exit 1 
        fi
        bundle exec rake strings:generate
        bundle exec rake lint
        if [ $? -eq 0 ]; then
          echo "Lint checks passed!"
        else
          echo "Lint checks failed!"
          exit 1
        fi

        
