name: Ruby Rake Tests
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Ruby
      uses: actions/setup-ruby
      with:
        ruby-version: 2.7
    - name: Install dependencies
      run: |
        bundle install
    - name: Run Rake tests
      run: |
        bundle exec rake test
